apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: u9i8md1qh-python
  janus-idp.io/tekton: u9i8md1qh-python
  backstage.io/kubernetes-id: u9i8md1qh-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: u9i8md1qh-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
